# Generated by Django 3.2.7 on 2021-12-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('body', models.TextField(default='')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='component order')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bg_color_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='page order')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Page',
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.component')),
            ],
            options={
                'db_table': 'banner',
            },
            bases=('pages.component',),
        ),
        migrations.CreateModel(
            name='CompanyRecord',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.component')),
            ],
            options={
                'db_table': 'companyrecord',
            },
            bases=('pages.component',),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.component')),
            ],
            options={
                'db_table': 'gallery',
            },
            bases=('pages.component',),
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(max_length=256)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='image order')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageimage', to='pages.component')),
            ],
            options={
                'db_table': 'pageimages',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component', to='pages.page'),
        ),
        migrations.CreateModel(
            name='CompanyDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=32, null=True)),
                ('company_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companydo', to='pages.companyrecord')),
            ],
            options={
                'db_table': 'companydo',
                'ordering': ['-year'],
            },
        ),
    ]
